// ─────────────────────────────────────────────────────────────────────────────
// joins.ts — Named type exports for all Ekthos domain entities
//
// WHY THIS FILE EXISTS:
//   database.types.ts is auto-generated by Supabase CLI and only exports generic
//   utility types (Tables<>, Enums<>). Hooks and pages need named types.
//   This file derives them from the generated types + defines join interfaces.
//
// KEEP IN SYNC WITH: database.types.ts (run `supabase gen types` after migrations)
// ─────────────────────────────────────────────────────────────────────────────

import type { Database } from '@/lib/database.types'

// ── Generic row helper ────────────────────────────────────────────────────────
type Row<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Row']

// ── Enums ─────────────────────────────────────────────────────────────────────
export type AppRoleDB = Database['public']['Enums']['app_role']
export type PersonStage = Database['public']['Enums']['person_stage']
export type ChurchRelationship = Database['public']['Enums']['church_relationship']
export type CellRole = Database['public']['Enums']['cell_role']
export type MinistryRole = Database['public']['Enums']['ministry_role']

// ── String literal unions (DB uses plain string columns) ─────────────────────

export type EventType =
  | 'culto'
  | 'celula'
  | 'retiro'
  | 'conferencia'
  | 'batismo'
  | 'casamento'
  | 'treinamento'
  | 'social'
  | 'reuniao'
  | 'outro'

export type DonationType =
  | 'dizimo'
  | 'oferta'
  | 'campanha'
  | 'missoes'
  | 'construcao'

export type DonationStatus =
  | 'pending'
  | 'confirmed'
  | 'failed'
  | 'refunded'
  | 'cancelled'

export type PaymentMethod =
  | 'pix'
  | 'cartao_credito'
  | 'cartao_debito'
  | 'boleto'
  | 'dinheiro'
  | 'transferencia'
  | 'outro'

export type ScheduleStatus =
  | 'draft'
  | 'published'
  | 'confirmed'
  | 'cancelled'
  | 'completed'

export type ChurchStatus =
  | 'onboarding'
  | 'configured'
  | 'suspended'

export type OnboardingStatus =
  | 'active'
  | 'completed'
  | 'abandoned'

export type StepStatus =
  | 'pending'
  | 'running'
  | 'done'
  | 'failed'
  | 'skipped'

// ── Base row types (direct table aliases) ────────────────────────────────────

export type Person             = Row<'people'>
export type PipelineStage      = Row<'pipeline_stages'>
export type Group              = Row<'groups'>
export type CellMember         = Row<'cell_members'>
export type CellMeeting        = Row<'cell_meetings'>
export type PastoralCabinet    = Row<'pastoral_cabinet'>
export type Ministry           = Row<'ministries'>
export type Volunteer          = Row<'volunteers'>
export type Donation           = Row<'donations'>
export type FinancialCampaign  = Row<'financial_campaigns'>
export type ChurchEvent        = Row<'church_events'>
export type ServiceSchedule    = Row<'service_schedules'>
export type Task               = Row<'tasks'>
export type Church             = Row<'churches'>
export type PipelineHistory    = Row<'pipeline_history'>
export type Interaction        = Row<'interactions'>

// ── Join interfaces (DB query results with relations) ─────────────────────────

/** people + current pipeline stage via person_pipeline */
export interface PersonWithStage extends Person {
  person_pipeline: Array<{
    stage_id: string
    last_activity_at: string | null
    entered_at?: string | null
    pipeline_stages: Pick<PipelineStage, 'id' | 'name' | 'slug' | 'order_index'> & {
      sla_hours?: number | null
    } | null
  }>
}

/** groups (cells) with member count + leader info */
export interface GroupWithDetails extends Group {
  cell_members: Array<Pick<CellMember, 'id' | 'role'>>
  leader: Pick<Person, 'id' | 'name' | 'phone' | 'email'> | null
}

/** ministries with the leader's person data */
export interface MinistryWithLeader extends Ministry {
  volunteer_count?: number
  leaders: {
    id: string
    church_id: string
    person_id: string
    role: string
    ministry_id: string
    is_active: boolean
    created_at: string
    updated_at: string
    people: Pick<Person, 'id' | 'name' | 'phone' | 'email'> | null
  } | null
}

/** volunteers with person info + ministry name */
export interface VolunteerWithPerson extends Volunteer {
  people: Pick<Person, 'id' | 'name' | 'phone' | 'email' | 'avatar_url'> | null
  ministries: Pick<Ministry, 'id' | 'name'> | null
}

/** service_schedules with assignments + volunteers + people */
export interface ScheduleAssignment {
  id: string
  church_id: string
  schedule_id: string
  volunteer_id: string
  role: string
  status: string
  notified_at: string | null
  responded_at: string | null
  created_at: string
  volunteers: {
    id: string
    role: string | null
    people: Pick<Person, 'id' | 'name' | 'phone' | 'email'> | null
    ministries?: Pick<Ministry, 'id' | 'name'> | null
  } | null
}

export interface ScheduleWithAssignments extends ServiceSchedule {
  ministries: Pick<Ministry, 'id' | 'name'> | null
  service_schedule_assignments: ScheduleAssignment[]
}

/** pastoral_cabinet with linked person */
export interface CabinetMemberWithPerson extends PastoralCabinet {
  people: Pick<Person, 'id' | 'name' | 'phone' | 'email'> | null
}

/** donations with person name */
export interface DonationWithPerson extends Donation {
  people: { id: string; name: string | null } | null
}

// ── Onboarding types (migrations 00012/00013 — not yet in generated types) ───

export interface OnboardingSession {
  id: string
  church_id: string | null
  user_id: string
  plan_slug: string | null
  status: OnboardingStatus
  block_index: number
  messages: Array<{ role: 'user' | 'assistant'; content: string; timestamp: string }>
  config_json: Record<string, unknown> | null
  created_at: string
  updated_at: string
}

export interface OnboardingStep {
  id: string
  session_id: string
  church_id: string | null
  step_number: number
  label: string
  status: StepStatus
  error_msg: string | null
  started_at: string | null
  completed_at: string | null
  created_at: string
  updated_at: string
}

export interface HealthScore {
  id: string
  church_id: string
  score: number
  components: Record<string, number> | null
  calculated_at: string
}

export interface ImpersonateSession {
  id: string
  admin_user_id: string
  church_id: string
  started_at: string
  ended_at: string | null
  notes: string | null
}
