-- ─────────────────────────────────────────────────────────────────────────────
-- Migration: seed_default_tags_pr1
-- INTENCIONALMENTE REVERTIDA — 2026-06-08
--
-- Decisão de produto (Felipe Abrantes, 2026-06-08):
--   Cada igreja cria suas próprias flags do zero, sem templates automáticos.
--   Não há defaults — o pastor começa com tabela vazia e define sua linguagem.
--   (Ver ADR-001: docs/adr/ADR-001-flags-configuráveis-por-igreja.md)
--
-- Esta migration foi aplicada em prod e os dados foram manualmente deletados.
-- O registro existe no log de migrations para tracking. O SQL abaixo é no-op.
-- ─────────────────────────────────────────────────────────────────────────────
SELECT 1; -- no-op intencional
